### ISSUE TITLE
Potential code injection problem

### ISSUE THREAD

**Issue by JamesColeman-AH** [TwisterMc/pdfjs-viewer-shortcode#10]
Hey Thomas McMahon,

I just wanted to share that the pdfjs/web/viewer.php file has a potential code injection problem. I would recommend changing the version outputs as follows:

```
<?php echo htmlentities($_GET["v"], ENT_QUOTES); ?>
```

**Comment by TwisterMc** [comment]
Will be fixed in the next version. Thanks

**Comment by TwisterMc** [comment]
Code has been patched. Let me know if you see any other issues.
