### ISSUE TITLE
Why this plug-in isn't using a more recent PDF.js version than 2.3.200?

### ISSUE THREAD

**Issue by Linvydas** [TwisterMc/pdfjs-viewer-shortcode#11]
Why in you plug-in you are using more than a year-old version of PDF.js? Compatibility issues or some other reason?

**Comment by TwisterMc** [comment]
Because that's what the plugin was using when I took it over. I tried an upgrade once and users ran into a lot of issues, so I reverted. I have plans to update it again, but haven't gotten to it yet.

**Comment by TwisterMc** [comment]
The PDFjs source code was updated a month or so ago to use  v 2.6.347.
