### ISSUE TITLE
An error occurred while loading the PDF

### ISSUE THREAD

**Issue by ELMOKS214** [TwisterMc/pdfjs-viewer-shortcode#16]
HI,

I need some help, all of the pages using the plugin got an error viewing the PDF.

Please see screen shots and link below:

![Screenshot (208)](https://user-images.githubusercontent.com/93690491/140241161-3dad111d-b5b3-44e1-afef-ecbf2555f4b7.png)

[pdfjs-viewer url="https%3A%2F%2Fwww.philippineconsulatela.org%2Fwp-content%2Fuploads%2F2021%2F08%2FADVISORY-Deadline-of-Overseas-Voter-Registration-Corrected-Date.pdf" viewer_width=100% viewer_height=800px fullscreen=true download=false print=false]

Thank you.

**Comment by TwisterMc** [comment]
The PDF should not be encoded in the editor. How did you generate that URL?

It should be `https://www.philippineconsulatela.org/wp-content/uploads/2021/08/ADVISORY-Deadline-of-Overseas-Voter-Registration-Corrected-Date.pdf` assuming your website starts with `https://www`

**Comment by ELMOKS214** [comment]
> The PDF should not be encoded in the editor. How did you generate that URL?
> 
> It should be `https://www.philippineconsulatela.org/wp-content/uploads/2021/08/ADVISORY-Deadline-of-Overseas-Voter-Registration-Corrected-Date.pdf` assuming your website starts with `https://www`

It was embedded using your pdfj plugin.

Thanks for the quick reply.

**Comment by TwisterMc** [comment]
Are you using the classic editor or the Gutenberg block? I'm trying to figure to how to re-create the issue.

**Comment by ELMOKS214** [comment]
> Are you using the classic editor or the Gutenberg block? I'm trying to figure to how to re-create the issue.

Below is the editor that im currently using right now, before I dont have a problem with the PDJF Viewer. 

![Screenshot (209)](https://user-images.githubusercontent.com/93690491/140246703-a97be296-4e2d-463f-b5df-b20811217977.png)

**Comment by TwisterMc** [comment]
Some encoding was done for security reasons. I'll do some digging to see if I can't figure out why you're seeing that.

Are you running the latest version? 2.1.2

**Comment by ELMOKS214** [comment]
> Some encoding was done for security reasons. I'll do some digging to see if I can't figure out why you're seeing that.
> 
> Are you running the latest version? 2.1.2

Yes, i have the latest version.

**Comment by TwisterMc** [comment]
I think it's a caching issue. Can you try clearing your cache?

**Comment by ELMOKS214** [comment]
> I think it's a caching issue. Can you try clearing your cache?

Cache cleared, same issue.

**Comment by TwisterMc** [comment]
I'll try to push a fix to break the cache incase that's the issue. Or maybe just pushing new files will magically make it work.

**Comment by ELMOKS214** [comment]
> I'll try to push a fix to break the cache incase that's the issue. Or maybe just pushing new files will magically make it work.

Thanks, looking forward for that magic.

**Comment by TwisterMc** [comment]
New version is up. Hopefully it works better.

**Comment by ELMOKS214** [comment]
> New version is up. Hopefully it works better.

Updated the plugin, error still there.

thanks for looking this up.

**Comment by TwisterMc** [comment]
There's nothing that's encoding the URL in my code. Could one of your other editor plugins be causing an issue? Have you made any other updates/additions recently?

**Comment by ELMOKS214** [comment]
I tried to disable the PDF embedder plugin. The cause is from multiple pdf plugins that I installed.

**Comment by TwisterMc** [comment]
So everything is working now?

**Comment by ELMOKS214** [comment]
Still the same, even i uninstalled all the plugin related to PDF embedder or viewer.

**Comment by TwisterMc** [comment]
Ok, I'll push out an update to decode that URL. Not sure what's going on.

**Comment by TwisterMc** [comment]
I released a new version of the plugin, give it a shot.
