### ISSUE TITLE
CSS Class

### ISSUE THREAD

**Issue by gioxx** [TwisterMc/pdfjs-viewer-shortcode#2]
Hi, is it possibile to set class on `$iframe_code` and `$fullscreen_link`?
I think it's important to manage elements using theme's CSS.

Thanks a lot in advance.

**Comment by TwisterMc** [comment]
The full screen link will have a class in the next update.

I can add a class to the iFrame too.

**Comment by gioxx** [comment]
Yes please! 😄 
Thanks in advance.

**Comment by TwisterMc** [comment]
This was completed. Closing.
