### ISSUE TITLE
Viewer window takes too much space on 320px width

### ISSUE THREAD

**Issue by printpagestopdf** [TwisterMc/pdfjs-viewer-shortcode#20]
If plugin is used on a device width of 320px the viewer window is too large to fit. Tested with viewer setting width=0 and all pdf page fit options.

Result: Pdf document not centered in screen, viewer has horizontal scrollbar.

**Comment by TwisterMc** [comment]
Unfortunately, that's a limitation of the core PDF library and that's managed by Mozilla. https://github.com/mozilla/pdf.js
