### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by ueen** [TwisterMc/pdfjs-viewer-shortcode#3]
If i choose a PDF it is inserted as http and will not load (mixed content), i have to manually change it to https which breaks the plugin settings in the editor.

**Comment by TwisterMc** [comment]
It's getting the URL from WordPress as every thing is going through the media library. Is the WordPress/Site Address (URL) in the Settings page set to https?

**Comment by ueen** [comment]
Great tipp, thanks, strange wordpress doesnt do this by default, considering i connected to the admin dashboard via https...

**Comment by ueen** [comment]
.
