### ISSUE TITLE
Uncaught Error: Call to un defined function register_block_type()

### ISSUE THREAD

**Issue by Now-Italy-Demo** [TwisterMc/pdfjs-viewer-shortcode#4]
Once updated to 1.5.1 on Wordpress 4.8.14 I get HTTP 500 due to Call to un defined function register_block_type() in pdfjs-viewer.php on line 158.

Fixed by changing line 158 to:

        if ( function_exists( 'register_block_type' ) )  {
                register_block_type('blocks/pdfjs-block', array(
                        'editor_script' => 'gutenberg-pdfjs',
                        'editor_style' => 'gutenberg-pdfjs-edit-style',
                        'style' => 'gutenberg-pdfjs'
                ));
        }

**Comment by TwisterMc** [comment]
Ok, I never tested in WordPress 4.x. I need to update the documentation to require 5.0 or make this work in WordPress 4.x.

Might I ask why you haven't updated to 5.x yet?

**Comment by TwisterMc** [comment]
I'll get this fix added to the next version.

**Comment by Now-Italy-Demo** [comment]
Unfortunately we have some customisations and will need to test the upgrade first..... basically didn't have the time yet :)

**Comment by Now-Italy-Demo** [comment]
Thanks for picking this up. I think it's no big deal to just fix the documentation. Just wanted to make you aware that on 4.x it has a problem. Cheers.

**Comment by octoxan** [comment]
We're running ClassicPress on a lot of our sites, so they don't have Gutenberg. Fixed this issue with https://github.com/TwisterMc/pdfjs-viewer-shortcode/pull/7 so it's compatible with both WP 4.x, 5.x, and all CP versions.

**Comment by TwisterMc** [comment]
Should be fixed and ready to go.
