### ISSUE TITLE
URLs being manipulated

### ISSUE THREAD

**Issue by gms199** [TwisterMc/pdfjs-viewer-shortcode#8]
When updating the 1.5.2 the plugin is no longer loading the PDFs properly.

I am using this shortcode 

[pdfjs-viewer url=https://octavosystems.com/octavosystems.com/wp-content/uploads/2020/04/OSD32MP1_BRK_SCH.pdf viewer_width=600px viewer_height=700px fullscreen=true download=true print=true]

I am getting this error message:

PDF.js v2.3.200 (build: 4ae3f9fc)
Message: Missing PDF "https://octavosystems.com/wp-content/uploads/2020/04/OSD32MP1_BRK_SCH.pdf".

it looks like the URL path is being manipulated to pull out the second octavosystems.com in the correct URL.

**Comment by erikwelsh** [comment]
Look like this is an issue in commit:

https://github.com/TwisterMc/pdfjs-viewer-shortcode/commit/084814438ec02cecc513c3358ae51cd98ac14fce

$file_name = str_replace( get_site_url(), '', $file_name );

will replace the site url as many times as it occurs in the file name.  In the above instance, this removes "octavosystems.com" multiple times from $file_name.  If the line is changed to:

$file_name = str_replace( get_site_url(), '', $file_name, 1 );

Then the site url will only be replaced once in $file_name, leaving any additional occurrences unchanged.

**Comment by TwisterMc** [comment]
I did not expect anyone to have their domain name in the URL twice. I've never seen that setup before. Is there a reason your site is setup this way? 

I'll have to think up a work around as we're trying to fix a bigger issue by removing the domain name from the PDF URL.

**Comment by gms199** [comment]
I think the installation was originally configured to support multisite but I am not sure.  Unfortunately it was done for us and I no longer have access to the person that set it up.

Right now we are commenting out the line the @erikwelsh pointed out.  That appears to fix our issue..

Thanks for the support.

**Comment by TwisterMc** [comment]
Ok, I'll look into just removing the first instance of the domain, hopefully that'll fix everyone's issues.

**Comment by TwisterMc** [comment]
I updated the plugin to only remove the first instance of the domain. Give it a whirl.

**Comment by gms199** [comment]
Thanks @TwisterMc.  I just checked my site and it appears to be having the same problem.  I checked what get_site_url() is returning and it is actually this: https://octavosystems.com/octavosystems.com.

So I don't think it is the two occurrences but how the final URL is rebuilt.  Let me know if you want me to test anything else out.

**Comment by TwisterMc** [comment]
I have an idea that I'll try to get pushed up soon. Currently I'm removing the site_url as set in WordPress when I should probably just be figuring out the domain and removing that.

**Comment by TwisterMc** [comment]
Ok, new version is up, hope it fixes the issue.

**Comment by gms199** [comment]
That looks like it fixed it!  Thanks for the awesome support.
