### ISSUE TITLE
Problem with new update

### ISSUE THREAD

**Issue by bobby3755** [TwisterMc/pdfjs-viewer-shortcode#9]
The new update that came out on 10/22/2020 created a "fatal error" within my site. Deactivating the plugin has been the expedient solution to this problem. Has this been happening for others as well? 

I am new to web development so don't know exactly what is going on here. Does anybody have some ideas as to what is going on here?

Also, is this the best place to ask this question?

**Comment by TwisterMc** [comment]
Do you know how to view the error logs on your server? I haven't heard of others having the issue and I didn't see it myself. Any details you can provide would be helpful as I'm not sure what would cause that.

**Comment by TwisterMc** [comment]
I have pushed a fix.

**Comment by bobby3755** [comment]
I tried activating the plugin again to see what error it would produce, but it seems to be working again. Thanks for the help!
